[project]
name = "template-repository"
version = "0.1.0"
description = "A template repository with dynamic README generation"
authors = [
    {name = "Your Name", email = "your.email@example.com"},
]
dependencies = [
    "Jinja2>=3.1.2",
]
