name: Build README

on:
  push:
    paths:
      - 'docs/readme/**'
      - 'pyproject.toml'
      - '.github/workflows/build-readme.yml'
      - 'src/**'
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.11"

jobs:
  build-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
      
      - name: Install package
        run: pip install -e .
      
      - name: Generate README
        run: python -m readme_generator readme
