name: Update File Structure

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/workflows/**'
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.11"

jobs:
  update-structure:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
      
      - name: Install package
        run: pip install -e .
      
      - name: Update structure
        run: python -m readme_generator structure
      
      - name: Trigger README rebuild
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sleep 5
          gh workflow run build-readme.yml || echo "Failed to trigger workflow directly, changes will be picked up by push trigger"
