name: Update File Structure

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/workflows/**'
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.11"
  VENV_PATH: .venv

jobs:
  update-structure:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
      
      - name: Cache virtual environment
        uses: actions/cache@v4
        id: venv-cache
        with:
          path: ${{ env.VENV_PATH }}
          key: venv-${{ runner.os }}-py${{ env.PYTHON_VERSION }}-${{ hashFiles('pyproject.toml', 'scripts/**') }}
          restore-keys: |
            venv-${{ runner.os }}-py${{ env.PYTHON_VERSION }}-
      
      - name: Create and activate virtual environment
        if: steps.venv-cache.outputs.cache-hit != 'true'
        run: |
          python -m venv ${{ env.VENV_PATH }}
          source ${{ env.VENV_PATH }}/bin/activate
          pip install tomli
      
      - name: Install local scripts
        run: |
          source ${{ env.VENV_PATH }}/bin/activate
          cd scripts && pip install -e .
      
      - name: Generate tree and update template
        run: |
          source ${{ env.VENV_PATH }}/bin/activate
          cd scripts && python generate_tree.py
      
      - name: Trigger README rebuild
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run build-readme.yml
